name: Update Medium stats to Gist
on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 * * * *" # update every 5mins
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update Medium stats to Gist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          MEDIUM_USER_NAME: ${{ secrets.MEDIUM_USER_NAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
