name: Update Medium stats to Gist
on:
  schedule:
    - cron: "5 * * * *" # update every 5mins
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update Medium stats to Gist
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
      - run: npm install
      - run: npm run start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          MEDIUM_USER_NAME: ${{ secrets.MEDIUM_USER_NAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
